### ISSUE TITLE
Starting an emulator with GPU emulation

### ISSUE THREAD

**Issue by tobrun** [bitrise-steplib/steps-start-android-emulator#22]
I'm currently looking into running some simple ui tests on Bitrise. 
For this I'm using this step to start the emulator. 
When I run an espresso test I'm running into:

``` java
com.mapbox.mapboxsdk.testapp.espresso.LatLngBoundsActivityTest > testSanity[test(AVD) - 6.0] FAILED 
    java.lang.Error: eglChooseConfig() failed
    at com.mapbox.mapboxsdk.maps.NativeMapView.nativeInitializeDisplay(Native Method)
Tests on test(AVD) - 6.0 failed: Instrumentation run failed due to 'java.lang.Error'
:MapboxGLAndroidSDKTestApp:connectedDebugAndroidTest FAILED
```

It seems that the current configuration doesn't allow to render OpenGL (TextureView, SurfaceView). At this point I'm thinking it has to do with starting the emulator without a graphical window.  
https://github.com/bitrise-steplib/steps-start-android-emulator/blob/master/step.rb#L153.

I'm able to run the tests on a similar device configuration locally with the graphical window.

**Comment by viktorbenei** [comment]
Did you try it without graphical window on your Mac/PC? Do you use an ARM or x86 emulator locally?

**Comment by tobrun** [comment]
@viktorbenei 
I have been doing some tests locally and noticed that `-gpu on` is missing from current setup. With this option enabled I'm able to run my test, without it fails creating a GL context. Is this something that could be added in a future version?

**Comment by viktorbenei** [comment]
You could try it by adding the params you need to the input `other_options`, that should work.

**Comment by tobrun** [comment]
@viktorbenei, I added it to `other_options`, but running into:

```
+------------------------------------------------------------------------------+
| (3) start-android-emulator@1.0.2                                             |
+------------------------------------------------------------------------------+
| id: start-android-emulator                                                   |
| version: 1.0.2                                                               |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| time: 2016-07-12T07:52:51Z                                                   |
+------------------------------------------------------------------------------+
|                                                                              |

Configs:
  emulator_name: test
  emulator_skin: 768x1280
  emulator_options: -gpu on

Starting emulator
  /opt/android-sdk-linux/tools/emulator64-arm -avd test -no-boot-anim -noaudio -no-window -skin 768x1280 -gpu on
resize2fs 1.42.13 (17-May-2015)
The filesystem is already 140800 (4k) blocks long.  Nothing to do!

emulator: WARNING: Increasing RAM size to 1GB
Creating filesystem with parameters:
    Size: 576716800
    Block size: 4096
    Blocks per group: 32768
    Inodes per group: 7040
    Inode size: 256
    Journal blocks: 2200
    Label: 
    Blocks: 140800
    Block groups: 5
    Reserved block group size: 39
Created filesystem with 11/35200 inodes and 4536/140800 blocks
Creating filesystem with parameters:
    Size: 69206016
    Block size: 4096
    Blocks per group: 32768
    Inodes per group: 4224
    Inode size: 256
    Journal blocks: 1024
    Label: 
    Blocks: 16896
    Block groups: 1
    Reserved block group size: 7
Created filesystem with 11/4224 inodes and 1302/16896 blocks
emulator: ERROR: Could not load OpenGLES emulation library [lib64OpenglRender]: lib64OpenglRender.so: cannot open shared object file: No such file or directory
emulator: ERROR: Could not initialize OpenglES emulation, use '-gpu off' to disable it.

Starting emulator timed out
```

Some [suggestions on SO](http://stackoverflow.com/a/19077946/1281750) related to this.

**Comment by viktorbenei** [comment]
Did you have time to test the SO solution? Seems promising.

**Comment by viktorbenei** [comment]
I believe this should work: http://stackoverflow.com/a/32440305/974381

Exporting an env var between steps can be done by using [envman](https://github.com/bitrise-io/envman), e.g. with a Script step (before the emulator step):

```
#!/bin/bash
set -ex
envman add --key LD_LIBRARY_PATH --value "$ANDROID_HOME/tools/lib64:$LD_LIBRARY_PATH"
```

**Comment by viktorbenei** [comment]
note: I'm not sure which `lib` should be included, either `$ANDROID_HOME/tools/lib64` or `$ANDROID_HOME/tools/lib`.

**Comment by tobrun** [comment]
First tests don't show the OpenGL anymore, but starting the emulator is still timing out, going to rerun the build and see if I can get it to run.

``` java
+------------------------------------------------------------------------------+
| (3) Setting env for gpu emulator                                             |
+------------------------------------------------------------------------------+
| id: script                                                                   |
| version: 1.1.1                                                               |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| time: 2016-07-13T13:42:52Z                                                   |
+------------------------------------------------------------------------------+
|                                                                              |
+ envman add --key LD_LIBRARY_PATH --value /opt/android-sdk-linux/tools/lib64:
|                                                                              |
+----+--------------------------------------------------------------+----------+
| ✅  | Setting env for gpu emulator                                 | 0.50 sec |
+----+--------------------------------------------------------------+----------+

                                          ▼

+------------------------------------------------------------------------------+
| (4) start-android-emulator@1.0.2                                             |
+------------------------------------------------------------------------------+
| id: start-android-emulator                                                   |
| version: 1.0.2                                                               |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| time: 2016-07-13T13:42:52Z                                                   |
+------------------------------------------------------------------------------+
|                                                                              |

Configs:
  emulator_name: test
  emulator_skin: 768x1280
  emulator_options: -gpu on

Starting emulator
  /opt/android-sdk-linux/tools/emulator64-arm -avd test -no-boot-anim -noaudio -no-window -skin 768x1280 -gpu on
resize2fs 1.42.13 (17-May-2015)
The filesystem is already 140800 (4k) blocks long.  Nothing to do!


Starting emulator timed out
|                                                                              |
+----+--------------------------------------------------------------+----------+
| 🚫  | start-android-emulator@1.0.2 (exit code: 1)                  | 804 sec  |
+----+--------------------------------------------------------------+----------+
| Issue tracker: ...ub.com/bitrise-steplib/steps-start-android-emulator/issues |
| Source: https://github.com/bitrise-steplib/steps-start-android-emulator      |
+----+--------------------------------------------------------------+----------+
```

**Comment by viktorbenei** [comment]
Thanks @tobrun ! Forgot to mention: of course, if you can provide us a sample repo and a template bitrise.yml we can dig into this too, if you'd need our help ;)

**Comment by tobrun** [comment]
@viktorbenei: I'm working from this branch: 
- https://github.com/mapbox/mapbox-gl-native/tree/5211-android-integraton-testing

within that branch and the android project you will find this `bitrise.yml`:

``` yml
---
format_version: 1.0.0
default_step_lib_source: https://github.com/bitrise-io/bitrise-steplib.git
trigger_map:
- pattern: scheduled
  workflow: scheduled
- pattern: "*"
  workflow: primary
workflows:
  primary:
    steps:
    - script:
        title: Check for skipping CI
        inputs:
        - content: |-
            #!/bin/bash

            if [[ -n "$(echo $GIT_CLONE_COMMIT_MESSAGE_SUBJECT | sed -n '/\[skip ci\]/p')"  ||
                  -n "$(echo $GIT_CLONE_COMMIT_MESSAGE_SUBJECT | sed -n '/\[ci skip\]/p')"  ||
                  -n "$(echo $GIT_CLONE_COMMIT_MESSAGE_BODY    | sed -n 's/\[skip ci\]/p')" ||
                  -n "$(echo $GIT_CLONE_COMMIT_MESSAGE_BODY    | sed -n 's/\[ci skip\]/p')" ]]; then
                envman add --key SKIPCI --value true
            else
                envman add --key SKIPCI --value false
            fi
    - create-android-emulator@0.9.1:
        inputs:
        - name: test
        - platform: android-23
    - script:
        title: Build
        run_if: '{{enveq "SKIPCI" "false"}}'
        inputs:
        - content: |-
            #!/bin/bash
            set -eu -o pipefail
            curl -sL https://deb.nodesource.com/setup_4.x | sudo -E bash -
            apt-get install -y pkg-config python-pip python-dev build-essential nodejs
            pip install awscli

            aws s3 cp s3://mapbox/android/ci-access-token/developer-config.xml platform/android/MapboxGLAndroidSDKTestApp/src/main/res/values/developer-config.xml

            export BUILDTYPE=Release
            make android
            make test-android
    - script:
        title: Setting env for gpu emulator
        inputs:
        - content: |-
            #!/bin/bash
            set -ex
            envman add --key LD_LIBRARY_PATH --value "$ANDROID_HOME/tools/lib64:$LD_LIBRARY_PATH"
    - start-android-emulator@1.0.2:
        inputs:
        - other_options: "-gpu on"
    - script:
        title: Run integragion tests
        run_if: '{{enveq "SKIPCI" "false"}}'
        inputs:
        - content: |-
            #!/bin/bash
            cd platform/android/
            ./gradlew -Pandroid.testInstrumentationRunnerArguments.class=com.mapbox.mapboxsdk.testapp.espresso.LatLngBoundsActivityTest connectedAndroidTest
    - slack:
        title: Post to Slack
        run_if: '{{enveq "SKIPCI" "false"}}'
        inputs:
        - webhook_url: "$SLACK_HOOK_URL"
        - channel: "#gl-bots"
        - from_username: 'Bitrise Android'
        - from_username_on_error: 'Bitrise Android'
        - message: '<${BITRISE_BUILD_URL}|Build #${BITRISE_BUILD_NUMBER}>
            for <https://github.com/mapbox/mapbox-gl-native/compare/${BITRISE_GIT_BRANCH}|mapbox/mapbox-gl-native@${BITRISE_GIT_BRANCH}>
            by ${GIT_CLONE_COMMIT_COMMITER_NAME}
            passed'
        - message_on_error: '<${BITRISE_BUILD_URL}|Build #${BITRISE_BUILD_NUMBER}>
            for <https://github.com/mapbox/mapbox-gl-native/compare/${BITRISE_GIT_BRANCH}|mapbox/mapbox-gl-native@${BITRISE_GIT_BRANCH}>
            by ${GIT_CLONE_COMMIT_COMMITER_NAME}
            failed'
        - icon_url: https://bitrise-public-content-production.s3.amazonaws.com/slack/bitrise-slack-icon-128.png
        - icon_url_on_error: https://bitrise-public-content-production.s3.amazonaws.com/slack/bitrise-slack-error-icon-128.png
  scheduled:
    steps:
    - script:
        title: Build
        inputs:
        - content: |-
            #!/bin/bash
            set -eu -o pipefail

            curl -sL https://deb.nodesource.com/setup_4.x | sudo -E bash -
            apt-get install -y pkg-config python-pip python-dev build-essential nodejs
            pip install awscli

            aws s3 cp s3://mapbox/android/signing-credentials/secring.gpg platform/android/MapboxGLAndroidSDK/secring.gpg

            echo "NEXUS_USERNAME=$PUBLISH_NEXUS_USERNAME
            NEXUS_PASSWORD=$PUBLISH_NEXUS_PASSWORD
            signing.keyId=$SIGNING_KEYID
            signing.password=$SIGNING_PASSWORD
            signing.secretKeyRingFile=secring.gpg" >> platform/android/MapboxGLAndroidSDK/gradle.properties

            export BUILDTYPE=Release
            make apackage

            cd platform/android
            ./gradlew uploadArchives
```

that is invoked by the following bitrise.yml:

``` yml
---
format_version: 1.1.0
default_step_lib_source: https://github.com/bitrise-io/bitrise-steplib.git
trigger_map:
- pattern: scheduled
  is_pull_request_allowed: false
  workflow: scheduled
- pattern: "*"
  is_pull_request_allowed: false
  workflow: primary
workflows:
  primary:
    steps:
    - git-clone:
        title: Git Clone
    - script:
        inputs:
        - content: |-
            #!/bin/bash
            bitrise trigger primary --config platform/android/bitrise.yml
        - is_debug: 'yes'
    before_run: 
    after_run: 
  scheduled:
    steps:
    - git-clone:
        title: Git Clone
        inputs:
        - branch: master
          opts:
            is_expand: false
    - script:
        inputs:
        - content: |-
            #!/bin/bash
            bitrise trigger scheduled --config platform/android/bitrise.yml
        - is_debug: 'yes'
    before_run: 
    after_run: 

```
